wandb:
  project: General Physics Model
  entity: wsnr-florian
  api_key: xxx
  id: test_run-4
  tags:
    - TestRun
  log_model: all # log :all", "parameters" or "gradients"
  log_interval: 100

logging:
  log_dir: /Users/zsa8rk/Coding/MetaPARC/logs
  log_file: null #log.txt
  log_level: INFO

model:
  architecture:
    name: Spatial-Temporal Transformer
    backbone: spatial temporal attention
    normalization: None
    activation: GELU
    patch_net: 2xConv3D

  input_channels: 5 # number of input fields (usually 5 (pressure, density, temperature, vel_x, vel_y))
  hidden_channels: 768 # number of hidden channels across all layers
  mlp_dim: 3072 # number of hidden channels in the MLP
  num_heads: 12 # number of attention heads
  dropout: 0.1 # dropout rate
  img_size: [4,256,128]
  patch_size: [4, 16, 16] # patch size (usually 4x16x16)
  tokenizer_mode: linear # tokenizer mode (usually linear or conv3d)
  num_layers: 12 # number of attention layers
  stochastic_depth: 0.1 # stochastic depth rate

training:
  batch_size: 64
  epochs: 100
  num_workers: 8
  grad_clip: 1.0 # gradient clipping
  optimizer:
    # name: Adam
    # betas: [0.9, 0.999]
    # learning_rate: 0.001
    # name: AdamW
    # learning_rate: 0.001
    # weight_decay: 0.01
    # betas: [0.9, 0.999]
    # name: DAdaptAdam
    # betas: [0.9, 0.999]
    # weight_decay: 0.01
    name: DAdaptAdamW
    betas: [0.9, 0.999]
    weight_decay: 0.01
  criterion:
    name: MSELoss

  # lr_scheduler:
  #   name: SequentialLR
  #   schedulers:
  #     - name: LinearLR # linear warmup scheduler
  #       start_factor: 0.001
  #       end_factor: 1.0
  #       total_iters: 10000 # number of training steps for linear warmup
  #     # - name: CosineAnnealingWarmRestarts # cosine annealing scheduler
  #     #   T_0: 10 # number epochs for one cosine annealing cycle
  #     #   T_mult: 2 # multiplicative factor for the number of epochs in each cycle
  #     #   min_lr: 0.0001
  #     - name: CosineAnnealingLR # cosine annealing scheduler
  #       T_max: 10 # Number of epochs for one cosine annealing cycle
  #       min_lr: 0.0001
data:
  dt_stride: 1 # take every dt_stride-th timestep
  n_steps_input: 4 # number of input timesteps
  n_steps_output: 1 # number of target timesteps
  out_shape: [256, 128] # output shape (usually 1x16x16)

  data_dir: /Users/zsa8rk/Coding/MetaPARC/data/datasets
  datasets:
    # - cylinder_sym_flow_water
    - cylinder_pipe_flow_water
    # - object_periodic_flow_water
    # - object_sym_flow_water
    # - object_sym_flow_air

    # - heated_flow_air

    # - turbulent_radiative_layer_2D
    # - rayleigh_benard
    # - shear_flow
    # - euler
